<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tf</string>
		<string>tfvars</string>
	</array>
	<key>name</key>
	<string>Terraform</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Comments</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.terraform</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Language constants (true, false, yes, no, on, off)</string>
			<key>match</key>
			<string>\b(true|false|yes|no|on|off)\b</string>
			<key>name</key>
			<string>constant.language.terraform</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>\b([0-9]+)([kKmMgG]b?)?\b</string>
			<key>name</key>
			<string>constant.numeric.terraform</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Hex numbers</string>
			<key>match</key>
			<string>\b(0x[0-9A-Fa-f]+)([kKmMgG]b?)?\b</string>
			<key>name</key>
			<string>constant.numeric.terraform</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.terraform</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.terraform</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.value.terraform</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.terraform</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.terraform</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.value.terraform</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.terraform</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.terraform</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(resource|data)\s+(")(\w+)(")\s+(")(.+)(")\s+({)</string>
			<key>name</key>
			<string>meta.resource.terraform</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.terraform</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.terraform</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.value.terraform</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.terraform</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.terraform</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(provider|provisioner|variable|output|module|atlas)\s+(")([\w-]+)(")\s+({)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.terraform</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Value assignments (left hand side not in double quotes)</string>
			<key>match</key>
			<string>([\w_-]+)\s*(=)\s*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.quote.double.terraform</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.assignment.terraform</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.quote.double.terraform</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Value assignments (left hand side in double quotes)</string>
			<key>match</key>
			<string>(")([\w_-]+)(")\s*(=)\s*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.terraform</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Maps</string>
			<key>match</key>
			<string>([\w\-_]+)\s+({)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.terraform</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.terraform</string>
	<key>uuid</key>
	<string>9060ca81-906d-4f19-a91a-159f4eb119d6</string>
</dict>
</plist>
