name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Read NodeJS version
        id: nodejs-version
        run: |
          content=`cat ./.nvmrc`
          echo "::set-output name=content::$content"

      - name: setup node
        uses: actions/setup-node@v1
        with:
          # See https://github.com/actions/setup-node/issues/32
          node-version: ${{ steps.nodejs-version.outputs.content }}

      - name: clean install dependencies
        run: npm ci    
      
      - name: compile and create vsix
        run: npm run package -- -o extension.vsix

      - name: upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: vscode-terraform-${{github.sha}}.vsix
          path: ${{github.workspace}}/extension.vsix
