name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: clean install dependencies
        run: npm ci

      - name: compile and create vsix
        run: npm run package -- -o extension.vsix

      - name: upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: vscode-terraform-${{github.sha}}.vsix
          path: ${{github.workspace}}/extension.vsix
