name: Publish Terraform VS Code Extension

on:
  push:
    branches:
      - master

jobs:
  publish_to_openvsx:
    name: publish to open-vsx.org
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npx ovsx publish
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
