name: Run syntax tests

on:
  push:
    branches:
      - main
    paths:
      - 'syntaxes/**'
      - 'tests/**'
  pull_request:
    branches:
      - main
    paths:
      - 'syntaxes/**'
      - 'tests/**'

jobs:
  syntax:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: npm install
        run: npm ci
      - name: syntax
        run: npm run test:syntax
